### ISSUE TITLE
actions return data in callback?

### ISSUE THREAD

**Issue by burdettadam** [Picolab/krl-node-modules#1]
In one of the examples an action returns data. Where does that data end up? Can it be access with the keyword setting?

**Comment by farskipper** [comment]
Yes with `setting`

For example, [example/myJsModule.js#L13-L22](https://github.com/Picolab/krl-node-modules/blob/8a17628fe1fa53b3447eabebbf0861debaf39b1d/example/myJsModule.js#L13-L22) is used like this:

```krl
myJsModule:bar(a, b) setting(data)
```
